version: '1.0'

container: none

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  images: 
    virtaus-testing:
      build: .
      ports:
        - "3000:3000"
      volumes: 
        - .:/app
        - /app/node_modules
      environment: 
        NODE_ENV: production
  test:
    build: .
    command: npm test
  script:
    - docker-compose build --pull
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  script:
    - docker-compose run --rm test

deploy:
  script:
    - echo "Deploying..."