version: '1.0'

container: none

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  # images: 
  #   virtaus-testing:
  #     build: .
  #     ports:
  #       - "3000:3000"
  #     volumes: 
  #       - .:/app
  #       - /app/node_modules
  #     environment: 
  #       NODE_ENV: production
  # test:
  #   build: .
  #   command: npm test
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  script:
    - npm run test --json --outputFile=./artifacts/test-results.json
  artifacts:
    paths: 
      - ./artifacts/test-results.json
    expire_in: 1 week

deploy:
  script:
    - echo "Deploying..."